language: node_js
node_js:
  - "10.3.0"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build --base-href https://p1xt.github.io/fcc-is-forked/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fcc-is-forked
  on:
    branch: master